#!/bin/bash
# FlowForge AI - Complete Setup Guide

echo "=========================================="
echo "FlowForge AI - Project Setup"
echo "=========================================="
echo ""

echo "1. BACKEND SETUP"
echo "---------------"
echo "cd backend"
echo "python main_flowforge.py"
echo ""
echo "Server will run on: http://localhost:8000"
echo ""

echo "2. FRONTEND SETUP"
echo "----------------"
echo "npm install"
echo "npm run dev"
echo ""
echo "Frontend will run on: http://localhost:3001"
echo ""

echo "3. OLLAMA SETUP (Required for LLM)"
echo "----------------------------------"
echo "Open a new terminal and run one of:"
echo ""
echo "Option A: Start Ollama service"
echo "  ollama serve"
echo ""
echo "Option B: Pull and run specific models"
echo "  ollama pull business-analyst"
echo "  ollama pull research-assistant"
echo "  ollama pull code-assistant"
echo "  ollama pull data-science-specialist"
echo "  ollama pull custom-ml-assistant"
echo "  ollama pull mistral"
echo ""
echo "Option C: Quick test with mistral"
echo "  ollama run mistral"
echo ""

echo "=========================================="
echo "ARCHITECTURE"
echo "=========================================="
echo ""
echo "MULTI-AGENT WORKFLOW:"
echo "  User Input"
echo "    |"
echo "    v"
echo "  [Planner] - business-analyst"
echo "    |"
echo "    v"
echo "  [Researcher] - research-assistant"
echo "    |"
echo "    v"
echo "  [Writer] - code-assistant"
echo "    |"
echo "    v"
echo "  [Reviewer] - data-science-specialist"
echo "    |"
echo "    v"
echo "  [Assembler] - custom-ml-assistant"
echo "    |"
echo "    v"
echo "  Final Output"
echo ""

echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Backend not responding?"
echo "  1. Check Ollama is running"
echo "  2. Verify port 8000 is free"
echo "  3. Check backend logs"
echo ""
echo "Frontend not loading?"
echo "  1. npm install (if first time)"
echo "  2. Clear browser cache"
echo "  3. Check frontend console (F12)"
echo ""
echo "Port already in use?"
echo "  Windows: Get-NetTCPConnection -LocalPort 8000 | Stop-Process"
echo "  Linux/Mac: lsof -i :8000 | awk 'NR!=1 {print $2}' | xargs kill"
echo ""

echo "=========================================="
echo "API ENDPOINTS"
echo "=========================================="
echo ""
echo "GET  /                    - Root"
echo "GET  /health              - Health check"
echo "POST /api/workflow/start  - Start workflow"
echo "GET  /api/workflow/status/{id} - Get status"
echo "GET  /api/workflow/result/{id} - Get result"
echo "GET  /api/workflows       - List workflows"
echo ""

echo "=========================================="
echo "CONFIGURATION"
echo "=========================================="
echo ""
echo "Backend: backend/.env"
echo "Frontend: vite.config.js"
echo ""
echo "Required Environment Variables:"
echo "  LLM_PROVIDER=ollama"
echo "  OLLAMA_BASE_URL=http://localhost:11434"
echo "  PLANNER_MODEL=business-analyst"
echo "  RESEARCHER_MODEL=research-assistant"
echo "  WRITER_MODEL=code-assistant"
echo "  REVIEWER_MODEL=data-science-specialist"
echo "  ASSEMBLER_MODEL=custom-ml-assistant"
echo ""

echo "=========================================="
echo "READY TO START!"
echo "=========================================="
echo ""
echo "Quick start (3 terminals):"
echo ""
echo "Terminal 1: ollama serve"
echo "Terminal 2: cd backend && python main_flowforge.py"
echo "Terminal 3: npm run dev"
echo ""
echo "Then visit: http://localhost:3001"
echo ""
