import { useState } from 'react'
import { motion } from 'framer-motion'
import { Download, Copy, CheckCircle, FileText, Target, Users, Palette, Calendar, TrendingUp } from 'lucide-react'
import Button from '../components/Button'
import Card from '../components/Card'
import { finalBriefData } from '../data/dummyData'

const FinalBrief = () => {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    const briefText = JSON.stringify(finalBriefData, null, 2)
    navigator.clipboard.writeText(briefText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const briefText = JSON.stringify(finalBriefData, null, 2)
    const blob = new Blob([briefText], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'marketing-brief.json'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const Section = ({ icon: Icon, title, children }) => (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="mb-8"
    >
      <div className="flex items-center gap-3 mb-4">
        <div className="bg-gradient-to-r from-neon-blue to-neon-purple p-2 rounded-lg">
          <Icon className="w-5 h-5 text-white" />
        </div>
        <h2 className="text-2xl font-bold text-white">{title}</h2>
      </div>
      <div className="ml-11">
        {children}
      </div>
    </motion.div>
  )

  return (
    <div className="relative min-h-screen overflow-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/3 right-1/3 w-96 h-96 bg-neon-purple/10 rounded-full blur-3xl" />
      </div>

      <div className="relative max-w-5xl mx-auto px-6 py-20">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 glass rounded-full mb-6">
            <CheckCircle className="w-4 h-4 text-neon-green" />
            <span className="text-sm font-medium text-gray-300">Generated Successfully</span>
          </div>
          
          <h1 className="text-5xl md:text-6xl font-bold text-white mb-4">
            Your <span className="text-gradient">Marketing Brief</span>
          </h1>
          <p className="text-xl text-gray-400">
            Complete, production-ready brief generated by AI agents
          </p>
        </motion.div>

        {/* Action Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="flex flex-wrap items-center justify-center gap-4 mb-12"
        >
          <Button size="lg" onClick={handleDownload}>
            <Download className="w-5 h-5" />
            Download Brief
          </Button>
          <Button variant="secondary" size="lg" onClick={handleCopy}>
            {copied ? (
              <>
                <CheckCircle className="w-5 h-5 text-neon-green" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-5 h-5" />
                Copy to Clipboard
              </>
            )}
          </Button>
        </motion.div>

        {/* Brief Content */}
        <Card variant="glass" className="border-2 border-neon-blue/30 shadow-glow">
          <div className="space-y-8">
            {/* Title & Date */}
            <div className="border-b border-white/10 pb-6">
              <h1 className="text-3xl font-bold text-white mb-2">
                {finalBriefData.projectTitle}
              </h1>
              <p className="text-gray-400">Generated on {finalBriefData.generatedDate}</p>
            </div>

            {/* Overview */}
            <Section icon={FileText} title="Overview">
              <p className="text-gray-300 leading-relaxed">
                {finalBriefData.overview}
              </p>
            </Section>

            {/* Objectives */}
            <Section icon={Target} title="Campaign Objectives">
              <ul className="space-y-2">
                {finalBriefData.objectives.map((obj, i) => (
                  <li key={i} className="flex items-start gap-3 text-gray-300">
                    <div className="w-1.5 h-1.5 bg-neon-blue rounded-full mt-2 flex-shrink-0" />
                    {obj}
                  </li>
                ))}
              </ul>
            </Section>

            {/* Target Audience */}
            <Section icon={Users} title="Target Audience">
              <div className="space-y-4">
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-2">Primary</h3>
                  <p className="text-gray-300">{finalBriefData.targetAudience.primary}</p>
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-2">Secondary</h3>
                  <p className="text-gray-300">{finalBriefData.targetAudience.secondary}</p>
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-2">Demographics</h3>
                  <p className="text-gray-300">{finalBriefData.targetAudience.demographics}</p>
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-2">Pain Points</h3>
                  <ul className="space-y-2">
                    {finalBriefData.targetAudience.painPoints.map((pain, i) => (
                      <li key={i} className="flex items-start gap-3 text-gray-300">
                        <div className="w-1.5 h-1.5 bg-neon-purple rounded-full mt-2 flex-shrink-0" />
                        {pain}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </Section>

            {/* Key Messages */}
            <Section icon={Target} title="Key Messages">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {finalBriefData.keyMessages.map((msg, i) => (
                  <Card key={i} variant="glassDark" className="text-center">
                    <p className="text-sm text-gray-300">{msg}</p>
                  </Card>
                ))}
              </div>
            </Section>

            {/* Ad Copy */}
            <Section icon={FileText} title="Ad Copy">
              <div className="space-y-4">
                <div className="glass-dark rounded-xl p-4">
                  <h3 className="text-sm font-semibold text-neon-purple mb-2">Headline</h3>
                  <p className="text-2xl font-bold text-white">{finalBriefData.adCopy.headline}</p>
                </div>
                <div className="glass-dark rounded-xl p-4">
                  <h3 className="text-sm font-semibold text-neon-purple mb-2">Subheadline</h3>
                  <p className="text-lg text-gray-300">{finalBriefData.adCopy.subheadline}</p>
                </div>
                <div className="glass-dark rounded-xl p-4">
                  <h3 className="text-sm font-semibold text-neon-purple mb-2">Body Copy</h3>
                  <p className="text-gray-300">{finalBriefData.adCopy.bodyPrimary}</p>
                </div>
                <div className="glass-dark rounded-xl p-4">
                  <h3 className="text-sm font-semibold text-neon-purple mb-2">Social Copy</h3>
                  <p className="text-gray-300">{finalBriefData.adCopy.bodySocial}</p>
                </div>
                <div className="glass-dark rounded-xl p-4">
                  <h3 className="text-sm font-semibold text-neon-purple mb-2">Call to Action</h3>
                  <p className="text-lg font-semibold text-neon-blue">{finalBriefData.adCopy.cta}</p>
                </div>
              </div>
            </Section>

            {/* Creative Direction */}
            <Section icon={Palette} title="Creative Direction">
              <div className="space-y-4">
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-2">Visual Theme</h3>
                  <p className="text-gray-300">{finalBriefData.creativeDirection.visualTheme}</p>
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-3">Color Palette</h3>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    {Object.entries(finalBriefData.creativeDirection.colorPalette).map(([name, color]) => (
                      <div key={name} className="glass-dark rounded-lg p-3">
                        <div 
                          className="w-full h-12 rounded mb-2"
                          style={{ backgroundColor: color.split(' ')[0] }}
                        />
                        <p className="text-xs text-gray-400 capitalize">{name}</p>
                        <p className="text-xs text-gray-500">{color}</p>
                      </div>
                    ))}
                  </div>
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-2">Imagery Guidelines</h3>
                  <ul className="space-y-2">
                    {finalBriefData.creativeDirection.imagery.map((img, i) => (
                      <li key={i} className="flex items-start gap-3 text-gray-300">
                        <div className="w-1.5 h-1.5 bg-neon-pink rounded-full mt-2 flex-shrink-0" />
                        {img}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-neon-blue mb-2">Design Style</h3>
                  <p className="text-gray-300">{finalBriefData.creativeDirection.designStyle}</p>
                </div>
              </div>
            </Section>

            {/* Channels */}
            <Section icon={TrendingUp} title="Marketing Channels">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {finalBriefData.channels.map((channel, i) => (
                  <Card key={i} variant="glassDark">
                    <h3 className="text-lg font-bold text-white mb-2">{channel.name}</h3>
                    <div className="space-y-2 text-sm">
                      <p className="text-gray-400">
                        <span className="text-neon-blue font-semibold">Budget:</span> {channel.budget}
                      </p>
                      <p className="text-gray-400">
                        <span className="text-neon-blue font-semibold">Goal:</span> {channel.goal}
                      </p>
                      <p className="text-gray-400">
                        <span className="text-neon-blue font-semibold">Creative:</span> {channel.creative}
                      </p>
                    </div>
                  </Card>
                ))}
              </div>
            </Section>

            {/* Posting Plan */}
            <Section icon={Calendar} title="4-Week Posting Plan">
              <div className="space-y-3">
                {Object.entries(finalBriefData.postingPlan).map(([week, plan]) => (
                  <div key={week} className="glass-dark rounded-lg p-4">
                    <h3 className="text-sm font-semibold text-neon-purple mb-1 capitalize">
                      {week.replace('week', 'Week ')}
                    </h3>
                    <p className="text-gray-300">{plan}</p>
                  </div>
                ))}
              </div>
            </Section>

            {/* Success Metrics */}
            <Section icon={Target} title="Success Metrics">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {Object.entries(finalBriefData.metrics).map(([metric, value]) => (
                  <Card key={metric} variant="glassDark" className="text-center">
                    <div className="text-2xl font-bold text-gradient mb-1">{value}</div>
                    <div className="text-xs text-gray-400 capitalize">{metric}</div>
                  </Card>
                ))}
              </div>
            </Section>
          </div>
        </Card>

        {/* Bottom Actions */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="mt-8 text-center"
        >
          <p className="text-gray-400 mb-4">
            Need to make changes? Create a new campaign or modify your inputs.
          </p>
          <Button variant="secondary" onClick={() => window.location.href = '/create'}>
            Create New Campaign
          </Button>
        </motion.div>
      </div>
    </div>
  )
}

export default FinalBrief
